import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "antd/dist/reset.css";
import "./globals.css";
import { FooterComponent } from "./components/footer.component";
import { AboutSession } from "./sessions/about.session";
import { BuilderSession } from "./sessions/builder.session";
import { HeaderComponent } from "./components/header.component";
import { IndicationsSession } from "./sessions/indications.session";
import { HomeSession } from "./sessions/home.session";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <head>{/* Metadata or other head elements */}</head>
      <body className={`${inter.variable} antialiased h-fit max-w-[1250px] mx-auto flex flex-col gap-28`}>
        <HeaderComponent />
        <HomeSession />
        <AboutSession />
        <IndicationsSession />
        <BuilderSession />
        <FooterComponent />
      </body>
    </html>
  );
}
