import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "antd/dist/reset.css";
import "./globals.css";
import { Footer } from "./sessions/footer.session";
import { AboutSession } from "./sessions/about.session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>{/* Metadata or other head elements */}</head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1250px] mx-auto`}>
        {children}
        <AboutSession />
        <Footer />
      </body>
    </html>
  );
}
